### ISSUE TITLE
Mob editing from home page

### ISSUE THREAD

**Issue by ANDREYDEN** [FRFlor/social-mob#30]
Mob editing window doesn't show previous topic and location.
![image](https://user-images.githubusercontent.com/25109066/83762641-c23db680-a645-11ea-8bfd-0cd912cfac6a.png)
![image](https://user-images.githubusercontent.com/25109066/83762698-cf5aa580-a645-11ea-951e-f20e980a8293.png)

**Comment by FRFlor** [comment]
Looks like a bug from my latest update, nice catch!
