### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by ANDREYDEN** [FRFlor/social-mob#31]
Would be awesome to have markdown support for mob descriptions

**Comment by ANDREYDEN** [comment]
[This](https://codesandbox.io/s/github/vuejs/vuejs.org/tree/master/src/v2/examples/vue-20-markdown-editor?from-embed=&file=/index.html) is what I found from the Vue samples

**Comment by FRFlor** [comment]
I try to avoid using v-html in my projects because it bypasses vue's escape protection. 

https://vuejs.org/v2/guide/security.html#Injecting-HTML

**Comment by FRFlor** [comment]
I think the downsides of bringing Markdown support out-weights the utility of it. Since the the cards are there just to briefly summarize topics anyway.

**Comment by ANDREYDEN** [comment]
Yeah, I agree. Maybe could be included in a future version, closing for now
